### PR TITLE
Add coveralls badge

### LINKED ISSUE #336: Add Build Status and Test Coverage Badges
Add test coverage badges to gisida and gisida-react repository. This will inform us on our progress in tests coverage.

### PR DESCRIPTION
**Pull request by kahummer**
Add's coveralls badge to gisida

### CODE REVIEW

**Comment by cKellyDesign** [comment]
@kahummer does this PR have a ticket? If not that's fine, let's just add a description to this PR

**Comment by kahummer** [comment]
fix: #336

**Comment by cKellyDesign** [comment]
@kahummer what's the status of this PR? Is it ready for review?

**Comment by kahummer** [comment]
@cKellyDesign The reports are being pushed to coveralls but the overall percentage is not being shown as is in other repositories. That's the remaining bit. I'd say it's on hold currently

**Pull request closed without merging**
